apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: my-namespace
data:
  APP_ENV: production
  APP_DEBUG: "false"

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: my-namespace
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly91c2VyOnBhc3N3b3JkQGRhdGFiYXNlLWhvc3Q6NTQzMg==  # Base64 encoded

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: my-namespace
data:
  POSTGRES_DB: mydatabase
  POSTGRES_USER: user

---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: my-namespace
type: Opaque
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQ=