apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: app-namespace
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXM=  # base64 encoded 'postgres'
  SPRING_DATASOURCE_PASSWORD: MTIzNDU2Nzg=  # base64 encoded '12345678'
