apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: app-namespace
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # base64 encoded 'postgres'
  POSTGRES_PASSWORD: MTIzNDU2Nzg=  # base64 encoded '12345678'

