apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: my-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: vasilkova/kiii-project:latest
          ports:
            - containerPort: 8080
          env:
            - name: CONFIG_VAR
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: CONFIG_VAR
            - name: SECRET_VAR
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SECRET_VAR
