apiVersion: v1
kind: Pod
metadata:
  name: postgres
  namespace: my-namespace
  labels:
    app: postgres
spec:
  containers:
    - name: postgres
      image: postgres:latest
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_PASSWORD
          value: "12345678"
