name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt-openjdk'

      - name: Run Tests
        run: mvn test

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }} .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}

      - name: Deploy to Kubernetes
        uses: azure/setup-kubectl@v1
        with:
          version: '1.25.0'
        run: |
          kubectl apply -f k8s-manifests/deployment.yaml
          kubectl apply -f k8s-manifests/service.yaml
          kubectl apply -f k8s-manifests/ingress.yaml
          kubectl apply -f k8s-manifests/statefulset.yaml
